"""empty message

Revision ID: b7c1e6e9a6cd
Revises: 0767f1809132
Create Date: 2024-09-20 21:45:07.962463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c1e6e9a6cd'
down_revision = '0767f1809132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences_set', sa.Boolean(), nullable=True))
        batch_op.drop_column('preferencer_set')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferencer_set', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('preferences_set')

    # ### end Alembic commands ###
